---
- hosts: all
  gather_facts: no
  become: yes
  remote_user: root
  tasks:

  - name: Get a list of running containers
    shell: docker ps -q | wc -l
    register: running_containers

  - name: Stop the running container
    shell: docker kill web
    when: running_containers.stdout == "1"
