---
- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
  - name: Stop and remove the running container
    command: sudo docker stop and rm my_container
    become_pass: "{{ lookup('file', 'vault_pass') }}"

